macro(add_option O DEF)
    if (DEFINED ${O})
        if (${${O}})
            set(${O} ON)
        else ()
            set(${O} OFF)
        endif()
    else ()
        set(${O} ${DEF})
    endif()
endmacro()

add_option(BUILD_SDF_OLD OFF)
add_option(BUILD_SDF_0018 OFF)
add_option(BUILD_SHARED_LIBS OFF)

if(BUILD_SDF_OLD)
    if(NOT "${CMAKE_SYSTEM_NAME}" MATCHES "Linux")
        message(FATAL "${CMAKE_SYSTEM_NAME} ${ARCHITECTURE} does not support by hardware secure module")
    endif()
    add_definitions(-DFSDF_OLD)
endif()

if(BUILD_SDF_0018)
    if(NOT "${CMAKE_SYSTEM_NAME}" MATCHES "Linux")
        message(FATAL "${CMAKE_SYSTEM_NAME} ${ARCHITECTURE} does not support by hardware secure module")
    endif()
    add_definitions(-DFSDF_0018)
endif()

macro(print_config NAME)
message("")
message("------------------------------------------------------------------------")
message("-- Configuring ${NAME} ${PROJECT_VERSION}${VERSION_SUFFIX}")
message("------------------------------------------------------------------------")
message("-- CMake              Cmake version and location   ${CMAKE_VERSION} (${CMAKE_COMMAND})")
message("-- Compiler           C++ compiler version         ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
message("-- TARGET_PLATFORM    Target platform              ${CMAKE_SYSTEM_NAME} ${ARCHITECTURE}")
message("-- BUILD_SHARED_LIBS  Build shard lib              ${BUILD_SHARED_LIBS}")
message("-- BUILD_SDF_OLD      Build SDF HSM                ${BUILD_SDF_OLD}")
message("-- BUILD_SDF_0018     Build SDF 0018               ${BUILD_SDF_0018}")
message("------------------------------------------------------------------------")
message("")
endmacro()